<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = [];
    public $timestamps = true;

    public function fromDateTime($value)
    {
        return strtotime(parent::fromDateTime($value)); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return mixed
     */
    public function selCustomer(array $data) {
        $customers = self::where('is_del', 1)
            ->where(function ($query) use ($data) {
                !empty($data['id']) && $query->where('id', $data['id']);
                isset($data['name']) && $query->where('name', 'like', '%'.$data['name'].'%');
                isset($data['source']) && $query->where('source', 'like', '%'.$data['source'].'%');
                isset($data['principal']) && $query->where('principal', 'like', '%'.$data['principal'].'%');
            })
            ->orderBy('id', 'desc')
            ->paginate(10);
        $pageHtml = $customers->links() ? $customers->links()->toHtml() : '';
        $customers = $customers->toArray();
        $customers['pageHtml'] = $pageHtml;
        return $customers;
    }

    /**
     * @param array $data
     * @return bool
     */
    public function addCustomer(array $data) {
        if($data['id']) {
            $affectedRows = self::where('id', $data['id'])->update($data);
            return $affectedRows ? true : false;
        }
        $customer = self::create($data);
        return $customer->id ? true : false;
    }
}
