<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    protected $guarded = [];
    public $timestamps = true;

    public function fromDateTime($value)
    {
        return strtotime(parent::fromDateTime($value)); // TODO: Change the autogenerated stub
    }

    public function addDomain(array $data) {
        if($data['id'] && !$data['pid']) {
            unset($data['pid']);
            $affectedRows = self::where('id', $data['id'])->update($data);
            return $affectedRows ? true : false;
        }
        unset($data['id']);
        $domain = self::create($data);
        return $domain->id ? true : false;
    }

    public function selDomain(array $data) {
        $domains = self::select('domains.*', 'c.id as c_id', 'c.name as c_name')
            ->where('domains.is_del', 1)
            ->where(function ($query) use ($data) {
                !empty($data['id']) && $query->where('domains.id', $data['id']);
                isset($data['owner']) && $query->where('c.name', 'like', '%'.$data['owner'].'%');
                isset($data['user']) && $query->where('domains.user', 'like', '%'.$data['user'].'%');
                !empty($data['pid']) && $query->where('domains.pid', $data['pid']);
                isset($data['name']) && $query->where('domains.name', 'like', '%'.$data['name'].'%');
            })
            ->leftJoin('customers as c', 'domains.customer_id', '=', 'c.id')
            ->orderBy('domains.id', 'desc')
            ->paginate(10);
        $pageHtml = $domains->links() ? $domains->links()->toHtml() : '';
        $domains = $domains->toArray();
        $domains['pageHtml'] = $pageHtml;
        return $domains;
    }
}
