<?php

namespace App\Models;

use App\Http\Requests\Request;
use Illuminate\Database\Eloquent\Model;

class Server extends Model
{
    protected $guarded = [];
    public $timestamps = true;

    public function fromDateTime($value)
    {
        return strtotime(parent::fromDateTime($value)); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $data
     * @return bool
     */
    public function addServer(array $data) {
        if($data['id']) {
            $affectedRows = self::where('id', $data['id'])->update($data);
            return $affectedRows ? true : false;
        }
        $server = self::create($data);
        return $server->id ? true : false;
    }

    /**
     * @param array $data
     * @return mixed
     */
    public function selServer(array $data) {
        $servers = self::select('servers.*', 'c.id as c_id', 'c.name')
            ->where('servers.is_del', 1)
            ->where(function ($query) use ($data) {
                !empty($data['id']) && $query->where('servers.id', $data['id']);
                isset($data['owner']) && $query->where('c.name', 'like', '%'.$data['owner'].'%');
            })
            ->leftJoin('customers as c', 'servers.customer_id', '=', 'c.id')
            ->orderBy('servers.id', 'desc')
            ->paginate(10);
        $pageHtml = $servers->links() ? $servers->links()->toHtml() : '';
        $servers = $servers->toArray();
        $servers['pageHtml'] = $pageHtml;
        return $servers;
    }
}
